### ISSUE TITLE
Add support for x509 logins

### ISSUE THREAD

**Issue by edwinavalos** [target/winnaker#14]
I'll probably work on this one myself in a bit, but I'm seeing an issue where the login page is failing in our implementation of ping federate, and easy way to avoid this would be to support x509 if enabled on your Spinnaker/Gate installs.

**Comment by medyagh** [comment]
do you mean support the default spinnaker login ? @edwinavalos

**Comment by edwinavalos** [comment]
x509 isn't the default login method, its the login method if you provide a client certificate. Lets you skip oauth2 or saml logins, but still trace the certificate to a user. It's nice if you don't particularly want to test logins, but just trigger pipelines.
