### ISSUE TITLE
Add ability to test multiple pipelines in sequence

### ISSUE THREAD

**Issue by edwinavalos** [target/winnaker#16]
Either a job file that winnaker can read, and do in sequence, or if you can provide more arguments in the command line would be nice for testing larger installations with different providers, and feature sets needing to be tested.

**Comment by medyagh** [comment]
it is better to just invoke winnaker -p a few times


``your_run_script.sh
winnaker -a "app1" -p "some pipleline name"
winnaker -a "app1" -p "some other pipleline name"
winnaker -a "app2" -p "another esxample"
```
thats better because it is better to start from a fresh chrome seassion than continuing on the other one. less errrors.
